#!/bin/sh

set -e -x

cd "${WORK}"
PATH="${WORK}/clang/bin:${WORK}/gcc/bin:/bin"

# Setup make Command
xxx() {
    ARCH=arm CC=clang HOSTCC=clang \
    CROSS_COMPILE=arm-linux-androideabi- \
    CLANG_TRIPLE=arm-linux-gnueabi- \
    KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y \
    CFLAGS_WARN=-Wunused-but-set-variable "$@"
}

# Start Compiling Kernel
cd "${KERNEL_SRC}"
mkdir -p out
make $xxx O=out "${KERNEL_DEFCONFIG}"
make $xxx O=out -j"$(nproc --all)" 2>&1 | tee build.log 
